services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"

  tests:
    build: .
    depends_on:
      - selenium
    environment:
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub